/* Show/Hide [ Header,Footer ] */
prevScrollpos=window.pageYOffset,window.onscroll=function(){var e=window.pageYOffset;prevScrollpos>e?(qS("header").style.top="15px",qS(".Mobile_Menu_Widget").style.bottom="15px"):(qS("header").style.top="-60px",qS(".Mobile_Menu_Widget").style.bottom="-60px"),prevScrollpos=e};
/* Image */
qSA(".onPost .postEntry img").forEach(a=>{aC(a,"lazyImg"),sAt(a,"s",a.src.replace(/\/s[0-9]+(\-c)?/,"/s1280-rw-e30")),sAt(a,"src","data:image/png;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs="),sAt(a,"alt",TS.Ts.pageTitle),sAt(a,"onclick","return false")});function wrap(t,r,A){qSA(r).forEach(a=>{a.outerHTML=t+a.outerHTML+A})}wrap('<div class="zmImg">',".postEntry img","</div>");qSA(".zmImg").forEach(a=>{a.onclick=function(){tC(this,"s"),event.preventDefault()}});
/* Lazy YouTube */
function YTIframe(e){var a=cE("iframe");sAt(a,"src","https://www.youtube.com/embed/"+gAt(e,"videoID")+"?autoplay=1&rel=0"),sAt(a,"frameborder","0"),sAt(a,"allowfullscreen",""),sAt(a,"allow","accelerometer;autoplay;encrypted-media;gyroscope;picture-in-picture"),e.parentNode.replaceChild(a,e)}function YTPlayer(){qSA(".YT-Player").forEach(e=>{var a=gAt(e,"videoID"),r=cE("div");sAt(r,"videoID",a);var l=cE("img");sAt(l,"alt",""),l.src="https://i.ytimg.com/vi/ID/hqdefault.jpg".replace("ID",a),r.appendChild(l);var i=cE("div");sAt(i,"class","Play"),r.appendChild(i),r.onclick=function(){YTIframe(this)},e.appendChild(r)})}aE(document,"DOMContentLoaded",YTPlayer);
/* Open Share Navigation */
function openShare(){navigator.share({title:TS.Ts.pageTitle,text:TS.Ts.pageTitle,url:TS.Ts.pageURL})}
/* Additional JS */
function tsLazyJs(){"true"==isSingleItem&&ldCSS("https://cdn.jsdelivr.net/gh/itsPuku/ts/tableofContent.css","toc-css",function(){ldJS("https://cdn.jsdelivr.net/gh/itsPuku/ts/tableofContent.js","toc-js",!0,"head",function(){new TableOfContents({from:qS("#postBody"),to:qS("#tocContent")}).generateToc()})}),"true"==isSingleItem&&ldCSS("https://cdn.jsdelivr.net/gh/itsPuku/ts/relatedPost.css","rPost-css",function(){ldJS("https://cdn.jsdelivr.net/gh/itsPuku/ts/relatedPost.js","rPost-js",!0,"head")}),"true"!=isError&&"lazy"==TS.adItems.loadType&&ldJS(TS.adItems.adPubURL,"ad-js",!0,"body"),lazyCJs()}var tsLazyLoad=!1;aE(window,"scroll",function(){(0!=document.documentElement.scrollTop&&!1===tsLazyLoad||0!=document.body.scrollTop&&!1===tsLazyLoad)&&(null==gLS("Lz_Js")&&(tsLazyJs(),sLS("Lz_Js",1)),"true"!=isError&&"scroll"==TS.adItems.loadType&&ldJS(TS.adItems.adPubURL,"ad-js",!0,"body"),tsLazyLoad=!0)},!0),aE(document.body,"click",t=>{null==gLS("Lz_Js")&&(tsLazyJs(),sLS("Lz_Js",1))}),gLS("Lz_Js")&&tsLazyJs();
